apiVersion: apps/v1
kind: Deployment

metadata:
  name: currency-conversion
  namespace: currency-prod

spec:
  replicas: 2

  selector:
    matchLabels:
      app: currency-conversion

  template:
    metadata:
      labels:
        app: currency-conversion

    spec:
      containers:
        - name: currency-conversion

          image: 890319878498.dkr.ecr.ap-south-1.amazonaws.com/currency-conversion:1.0

          ports:
            - containerPort: 8100