apiVersion: v1
kind: Service

metadata:
  name: currency-exchange
  namespace: currency-prod

spec:
  selector:
    app: currency-exchange

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

  type: ClusterIP